### ISSUE TITLE
连续查询几个小时后报错

### ISSUE THREAD

**Issue by Asterisci** [gzldc/12306#1]
连续查询几个小时后报错，疑似和tk过期有关

```
empty range for randrange()
```

目前我观察到tk过期非常频繁，平均只能查询几十分钟左右，希望能改进登录方式

**Comment by gzldc** [comment]
感谢您的问题，因为阿里的滑块验证跳过比较困难，这个tk也只是暂时的。如果有新的方式会及时更新。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gzldc/12306"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月26日(星期六) 晚上9:01
收件人:&nbsp;"gzldc/12306"<12306@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[gzldc/12306] 连续查询几个小时后报错 (#1)





 
连续查询几个小时后报错，疑似和tk过期有关
 empty range for randrange()  
目前我观察到tk过期非常频繁，平均只能查询几十分钟左右，希望能改进登录方式
